apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web
  labels: # Метки в формате key: value
    nginx: latest
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
  - name: web-container # Название контейнера
    image: "bulkak/bulkak-platform-nginx" # Образ из которого создается контейнер
    volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
  - name: init-container
    image: "busybox:1.31.0"
    command:
      ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app
  volumes:
    - name: app
      emptyDir: {}